---
- name: Install tomcat in ec2-user
  hosts: dockerservers
  gather_facts: false
  become: yes

  tasks:
    - name: Check uptime and date
      command: "date"
      register: a
    - debug:
        var: a.stdout_lines
    - name: Install the  of java
      shell: |
         yum install java -y
    - name: Install the latest version of tomcat
      shell: |
         yum install httpd -y

    - name: Add the current user to the docker group
      user:
        name: ec2-user
        groups: tomcat
        append: yes

  handlers:
    - name: Start and enable tomcat
      service:
        name: docker
        state: started
        enabled: yes
