---
- name: Install tomcat in ec2-user
  hosts: dockerservers
  gather_facts: false
  become: yes

  tasks:
    - name: Check uptime and date
      command: "date"
      register: a
    - debug:
        var: a.stdout_lines
    - name: Install the  of java
      shell: |
         yum install java -y
    - name: Install the latest version of tomcat
      shell: |
         yum install httpd -y && service httpd start
    - name: Copy the war file  
      copy:  
        src: /home/sonar/workspace/ansible test pileline/index.html  
        dest: /var/www/html 

    - name: Add the current user to the docker group
      user:
        name: ec2-user
        groups: tomcat
        append: yes

